"""文章表

Revision ID: 43c8b531af6b
Revises: b1bf0bc81fc0
Create Date: 2018-07-10 17:50:36.392645

"""

# revision identifiers, used by Alembic.
revision = '43c8b531af6b'
down_revision = 'b1bf0bc81fc0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_index(op.f('ix_mywords_set_id'), 'mywords', ['set_id'], unique=False)
    # op.drop_index('ix_mywords_set', table_name='mywords')
    op.add_column('passages', sa.Column('passage_short', sa.String(length=1024), nullable=True))
    op.add_column('passages', sa.Column('title', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('passages', 'title')
    op.drop_column('passages', 'passage_short')
    # op.create_index('ix_mywords_set', 'mywords', ['set_id'], unique=False)
    # op.drop_index(op.f('ix_mywords_set_id'), table_name='mywords')
    # ### end Alembic commands ###
