"""扩大interpret.type的字段长度

Revision ID: 5f3699844150
Revises: 233774887615
Create Date: 2018-07-03 13:49:08.783027

"""

# revision identifiers, used by Alembic.
revision = '5f3699844150'
down_revision = '233774887615'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
