"""2018-8-23 add favorite words

Revision ID: 9442dfa3e7fd
Revises: 70d234ee3a0c
Create Date: 2018-08-23 23:10:00.671400

"""

# revision identifiers, used by Alembic.
revision = '9442dfa3e7fd'
down_revision = '70d234ee3a0c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('my_favorite_words',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('word', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_my_favorite_words_user_id'), 'my_favorite_words', ['user_id'], unique=False)
    op.create_index(op.f('ix_my_favorite_words_word'), 'my_favorite_words', ['word'], unique=False)
    op.create_table('my_favorite_words_st',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('word_id', sa.Integer(), nullable=False),
    sa.Column('passage_id', sa.Integer(), nullable=False),
    sa.Column('sentence', sa.String(length=1024), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_my_favorite_words_st_passage_id'), 'my_favorite_words_st', ['passage_id'], unique=False)
    op.create_index(op.f('ix_my_favorite_words_st_word_id'), 'my_favorite_words_st', ['word_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_my_favorite_words_st_word_id'), table_name='my_favorite_words_st')
    op.drop_index(op.f('ix_my_favorite_words_st_passage_id'), table_name='my_favorite_words_st')
    op.drop_table('my_favorite_words_st')
    op.drop_index(op.f('ix_my_favorite_words_word'), table_name='my_favorite_words')
    op.drop_index(op.f('ix_my_favorite_words_user_id'), table_name='my_favorite_words')
    op.drop_table('my_favorite_words')
    # ### end Alembic commands ###
