"""生成音标

Revision ID: a8bf77cf858b
Revises: e56a7d3f6e2d
Create Date: 2018-07-10 10:35:06.474575

"""

# revision identifiers, used by Alembic.
revision = 'a8bf77cf858b'
down_revision = 'e56a7d3f6e2d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('words', sa.Column('note', sa.String(length=1024), nullable=True))
    op.add_column('words', sa.Column('phonetics', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('words', 'phonetics')
    op.drop_column('words', 'note')
    # ### end Alembic commands ###
