"""change size

Revision ID: aade084c0efc
Revises: 5f3699844150
Create Date: 2018-07-03 15:49:20.743690

"""

# revision identifiers, used by Alembic.
revision = 'aade084c0efc'
down_revision = '5f3699844150'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
