"""我的单词库

Revision ID: b1bf0bc81fc0
Revises: a8bf77cf858b
Create Date: 2018-07-10 15:30:53.915377

"""

# revision identifiers, used by Alembic.
revision = 'b1bf0bc81fc0'
down_revision = 'a8bf77cf858b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mywords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('word', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('set_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mywords_word'), 'mywords', ['word'], unique=False)
    op.create_index(op.f('ix_mywords_set'), 'mywords', ['set_id'], unique=False)
    op.create_table('word_set',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('set_desc', sa.String(length=1024), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('word_set')
    op.drop_index(op.f('ix_mywords_word'), table_name='mywords')
    op.drop_table('mywords')
    # ### end Alembic commands ###
