"""生成解释例句

Revision ID: cc0e9db443ea
Revises: 7c2e3dec4856
Create Date: 2018-06-29 21:22:08.666581

"""

# revision identifiers, used by Alembic.
revision = 'cc0e9db443ea'
down_revision = '7c2e3dec4856'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('word_interpretation_example',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('interpretation_id', sa.Integer(), nullable=True),
    sa.Column('example', sa.String(length=1024), nullable=False),
    sa.ForeignKeyConstraint(['interpretation_id'], ['word_interpretation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_word_interpretation_example_interpretation_id'), 'word_interpretation_example', ['interpretation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_word_interpretation_example_interpretation_id'), table_name='word_interpretation_example')
    op.drop_table('word_interpretation_example')
    # ### end Alembic commands ###
