"""create table myufwords

Revision ID: d80f981410e8
Revises: dc0b6b28fb75
Create Date: 2018-07-12 17:39:39.718919

"""

# revision identifiers, used by Alembic.
revision = 'd80f981410e8'
down_revision = 'dc0b6b28fb75'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('myufwords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('word', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_myufwords_word'), 'myufwords', ['word'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_myufwords_word'), table_name='myufwords')
    op.drop_table('myufwords')
    # ### end Alembic commands ###
