"""2018-10-03 update the favorite words sentences

Revision ID: dfef6332f238
Revises: 9442dfa3e7fd
Create Date: 2018-10-03 17:20:51.676366

"""

# revision identifiers, used by Alembic.
revision = 'dfef6332f238'
down_revision = '9442dfa3e7fd'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('my_favorite_words_st', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('my_favorite_words_st', sa.Column('word', sa.String(length=64), nullable=False))
    op.alter_column('my_favorite_words_st', 'passage_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.create_index(op.f('ix_my_favorite_words_st_user_id'), 'my_favorite_words_st', ['user_id'], unique=False)
    op.create_index(op.f('ix_my_favorite_words_st_word'), 'my_favorite_words_st', ['word'], unique=False)
    op.drop_index('ix_my_favorite_words_st_passage_id', table_name='my_favorite_words_st')
    op.drop_index('ix_my_favorite_words_st_word_id', table_name='my_favorite_words_st')
    op.drop_column('my_favorite_words_st', 'word_id')
    # op.create_index(op.f('ix_mywords_set_id'), 'mywords', ['set_id'], unique=False)
    # op.drop_index('ix_mywords_set', table_name='mywords')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_mywords_set', 'mywords', ['set_id'], unique=False)
    op.drop_index(op.f('ix_mywords_set_id'), table_name='mywords')
    op.add_column('my_favorite_words_st', sa.Column('word_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.create_index('ix_my_favorite_words_st_word_id', 'my_favorite_words_st', ['word_id'], unique=False)
    op.create_index('ix_my_favorite_words_st_passage_id', 'my_favorite_words_st', ['passage_id'], unique=False)
    op.drop_index(op.f('ix_my_favorite_words_st_word'), table_name='my_favorite_words_st')
    op.drop_index(op.f('ix_my_favorite_words_st_user_id'), table_name='my_favorite_words_st')
    op.alter_column('my_favorite_words_st', 'passage_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    # op.drop_column('my_favorite_words_st', 'word')
    # op.drop_column('my_favorite_words_st', 'user_id')
    # ### end Alembic commands ###
