"""table example add column word_id

Revision ID: e56a7d3f6e2d
Revises: aade084c0efc
Create Date: 2018-07-04 07:41:48.952466

"""

# revision identifiers, used by Alembic.
revision = 'e56a7d3f6e2d'
down_revision = 'aade084c0efc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('word_interpretation_examples', sa.Column('word_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_word_interpretation_examples_word_id'), 'word_interpretation_examples', ['word_id'], unique=False)
    op.create_foreign_key(None, 'word_interpretation_examples', 'words', ['word_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'word_interpretation_examples', type_='foreignkey')
    op.drop_index(op.f('ix_word_interpretation_examples_word_id'), table_name='word_interpretation_examples')
    op.drop_column('word_interpretation_examples', 'word_id')
    # ### end Alembic commands ###
