"""创建单词表

Revision ID: ed53cb6cf1cd
Revises: 51f5ccfba190
Create Date: 2018-06-17 14:35:58.782983

"""

# revision identifiers, used by Alembic.
revision = 'ed53cb6cf1cd'
down_revision = '51f5ccfba190'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('passages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('passage', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sentences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('sentence', sa.String(length=1024), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('word_interpretation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('word_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=16), nullable=True),
    sa.Column('interpretation', sa.String(length=1024), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_word_interpretation_type'), 'word_interpretation', ['type'], unique=False)
    op.create_index(op.f('ix_word_interpretation_word_id'), 'word_interpretation', ['word_id'], unique=False)
    op.create_table('words',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('word', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_words_word'), 'words', ['word'], unique=False)
    op.create_table('words_in_sentence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('word_id', sa.Integer(), nullable=True),
    sa.Column('sentence_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_words_in_sentence_sentence_id'), 'words_in_sentence', ['sentence_id'], unique=False)
    op.create_index(op.f('ix_words_in_sentence_word_id'), 'words_in_sentence', ['word_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_words_in_sentence_word_id'), table_name='words_in_sentence')
    op.drop_index(op.f('ix_words_in_sentence_sentence_id'), table_name='words_in_sentence')
    op.drop_table('words_in_sentence')
    op.drop_index(op.f('ix_words_word'), table_name='words')
    op.drop_table('words')
    op.drop_index(op.f('ix_word_interpretation_word_id'), table_name='word_interpretation')
    op.drop_index(op.f('ix_word_interpretation_type'), table_name='word_interpretation')
    op.drop_table('word_interpretation')
    op.drop_table('sentences')
    op.drop_table('passages')
    # ### end Alembic commands ###
